package org.phoenix.wallet.addressManager;

import org.phoenix.passwords.PasswordFailException;
import org.phoenix.wallet.keys.Keypair;
import org.phoenix.wallet.keys.LinearKeyManager;
import org.phoenix.wallet.keys.PublicKey;
import org.phoenix.wallet.keys.SequentialKeyManager;

import java.util.Collection;
import java.util.LinkedList;

/**
 * Created by dragonfly on 3/18/14.
 */
public class Bip32LinearAddressManager extends AddressManagerAbstract implements LinearAddressManager {
    private LinkedList<LinearKeyManager> keys;

    @Override
    public Iterable<PublicKey> latest() {
        //TODO autogenerated.
        return null;
    }

    @Override
    public void generate_next() {
        //TODO autogenerated.

    }

    @Override
    public SequentialKeyManager export_SequentialKeyManager(int manager) {
        return keys.get(manager).export_SequentialKeyManager();
    }

    @Override
    public PublicKey get_PublicKey(int manager, int n) {
        return keys.get(manager).get_PublicKey(n);
    }

    @Override
    public Keypair get_PrivateKey(int manager, int n) throws PasswordFailException {
        return keys.get(manager).get_PrivateKey(n);
    }

    @Override
    public LinearKeyManager export_LinearKeyManager(int manager, int n) {
        return keys.get(manager).export_LinearKeyManager(n);
    }

    @Override
    public LinearAddressManager export_LinearAddressManager(int n) {
        //TODO autogenerated.
        return null;
    }

    @Override
    public Collection<String> get_addresses() {
        //TODO autogenerated.
        return null;
    }
}
