package org.phoenix.wallet.addressManager;

import org.phoenix.passwords.PasswordFailException;
import org.phoenix.wallet.keys.*;

import java.util.Collection;

/**
 * Created by dragonfly on 3/18/14.
 */
public class Bip32BeadedCurtainAddressManager extends AddressManagerAbstract implements BeadedCurtainAddressManager{
    @Override
    public PublicKey get_PublicKey(int manager, int n, int m) {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public Keypair get_PrivateKey(int manager, int n, int m) throws PasswordFailException {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public BeadedCurtainKeyManager export_BeadedCurtainKeyManager(int manager) {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public BeadedCurtainKeyManager export_private_BeadedCurtainKeyManager(int manager) throws PasswordFailException {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public BeadedCurtainKeyManager export_BeadedCurtainAddressManager() {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public BeadedCurtainKeyManager export_private_BeadedCurtainAddressManager() throws PasswordFailException {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public LinearKeyManager export_LinearKeyManager() {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public LinearKeyManager export_private_LinearKeyManager() throws PasswordFailException {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public LinearKeyManager export_LinearKeyManager(int n) {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public LinearKeyManager export_private_LinearKeyManager(int n) throws PasswordFailException {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public int length() {
        //TODO: autogenerated.
        return 0;
    }

    @Override
    public int chain_length(int n) {
        //TODO: autogenerated.
        return 0;
    }

    @Override
    public SequentialKeyManager export_SequentialKeyManager(int n, int m) {
        //TODO: autogenerated.
        return null;
    }

    @Override
    public Collection<String> get_addresses() {
        //TODO: autogenerated.
        return null;
    }
}
